/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ybs_eczane;

import puanlama_ekleme.yeni_ekle;
import static com.sun.org.apache.xalan.internal.xsltc.compiler.util.Type.Boolean;
import java.awt.PopupMenu;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import puanlama_ekleme.db_work;
import baglanti.baglan;
import sun.misc.FpUtils;


/**
 *
 * @author loop
 */
public class anket_arayüz extends javax.swing.JFrame {

    /**
     * Creates new form anket_arayüz
     */
    public anket_arayüz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        hst_adi = new javax.swing.JTextField();
        hst_soyadi = new javax.swing.JTextField();
        hst_yas = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        teraflu_chkbox = new javax.swing.JCheckBox();
        parol_chkbox = new javax.swing.JCheckBox();
        majezik_chkbox = new javax.swing.JCheckBox();
        aferin_chkbox = new javax.swing.JCheckBox();
        sistenol_chkbox = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        siklik = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        bas_agrisi = new javax.swing.JCheckBox();
        mide_bulantisi = new javax.swing.JCheckBox();
        bas_dönmesi = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        iyi_box = new javax.swing.JCheckBox();
        kotu_box = new javax.swing.JCheckBox();
        gonder = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        istah_chcboz = new javax.swing.JCheckBox();
        baygın_chcbx = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel1.setText("Eczane İlaç Sistemi");

        jLabel2.setText("Sağlıklı yönlendirme için soruları eksiksiz ve doğru şekilde cevaplayınız.");

        jLabel3.setText("Adınız:");

        jLabel4.setText("Soyadınız:");

        jLabel5.setText("Yaşınız: ");

        hst_adi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hst_adiActionPerformed(evt);
            }
        });

        hst_soyadi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hst_soyadiActionPerformed(evt);
            }
        });

        hst_yas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hst_yasActionPerformed(evt);
            }
        });

        jLabel6.setText("Kullanıcı Dönütü");

        jLabel7.setText("Kullandığınız ilacı seçiniz:");

        teraflu_chkbox.setText("TERAFLU");
        teraflu_chkbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teraflu_chkboxActionPerformed(evt);
            }
        });

        parol_chkbox.setText("PAROL");
        parol_chkbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parol_chkboxActionPerformed(evt);
            }
        });

        majezik_chkbox.setText("MAJEZİK");
        majezik_chkbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                majezik_chkboxActionPerformed(evt);
            }
        });

        aferin_chkbox.setText("AFERİN");
        aferin_chkbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aferin_chkboxActionPerformed(evt);
            }
        });

        sistenol_chkbox.setText("SiSTENOL");
        sistenol_chkbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sistenol_chkboxActionPerformed(evt);
            }
        });

        jLabel9.setText("Günde ne sıklıkla kullanıyorsunuz? ");

        siklik.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        siklik.setToolTipText("");
        siklik.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        siklik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siklikActionPerformed(evt);
            }
        });

        jLabel10.setText("Ne gibi hastalık  belirtileri gösteriyorsunuz seçiniz ?");

        bas_agrisi.setText("Baş Ağrısı");
        bas_agrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bas_agrisiActionPerformed(evt);
            }
        });

        mide_bulantisi.setText("Mide Bulantısı");
        mide_bulantisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mide_bulantisiActionPerformed(evt);
            }
        });

        bas_dönmesi.setText("Baş Dönmesi");
        bas_dönmesi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bas_dönmesiActionPerformed(evt);
            }
        });

        jLabel8.setText("İlacın nasıl etkilediğini seçiniz ? ");

        iyi_box.setText("İiyi");
        iyi_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iyi_boxActionPerformed(evt);
            }
        });

        kotu_box.setText("Kötü");
        kotu_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kotu_boxActionPerformed(evt);
            }
        });

        gonder.setText("Gönder");
        gonder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gonderActionPerformed(evt);
            }
        });

        jLabel12.setText("Lütfen yan taraftan hangi ilaç üzerine işlem yapmak istediğinizi seçiniz.");

        istah_chcboz.setText("İştahsızlık");
        istah_chcboz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                istah_chcbozActionPerformed(evt);
            }
        });

        baygın_chcbx.setText("Baygınlık");
        baygın_chcbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baygın_chcbxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(36, 36, 36)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(hst_adi, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(hst_soyadi, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(hst_yas, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(33, 33, 33)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(144, 144, 144)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel10)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(teraflu_chkbox)
                                        .addGap(57, 57, 57)
                                        .addComponent(parol_chkbox)
                                        .addGap(33, 33, 33)
                                        .addComponent(majezik_chkbox))
                                    .addComponent(jLabel7)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(siklik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(68, 68, 68)
                                        .addComponent(aferin_chkbox)
                                        .addGap(43, 43, 43)
                                        .addComponent(sistenol_chkbox))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(bas_agrisi)
                                        .addGap(29, 29, 29)
                                        .addComponent(mide_bulantisi)
                                        .addGap(26, 26, 26)
                                        .addComponent(bas_dönmesi))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(iyi_box)
                                        .addGap(29, 29, 29)
                                        .addComponent(kotu_box)))))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(istah_chcboz)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(baygın_chcbx)
                        .addGap(143, 143, 143))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(215, 215, 215))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(gonder, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(118, 118, 118))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(hst_adi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(hst_soyadi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(hst_yas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(sistenol_chkbox)
                                    .addComponent(aferin_chkbox)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(teraflu_chkbox)
                                    .addComponent(parol_chkbox)
                                    .addComponent(majezik_chkbox))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(siklik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(iyi_box)
                            .addComponent(kotu_box))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bas_agrisi)
                            .addComponent(mide_bulantisi)
                            .addComponent(bas_dönmesi))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(istah_chcboz)
                            .addComponent(baygın_chcbx))
                        .addGap(35, 35, 35)
                        .addComponent(gonder, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hst_adiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hst_adiActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_hst_adiActionPerformed

    private void teraflu_chkboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teraflu_chkboxActionPerformed
        // TODO add your handling code here:
        
        aferin_chkbox.setSelected(false);
        sistenol_chkbox.setSelected(false);
        majezik_chkbox.setSelected(false);
        parol_chkbox.setSelected(false);
        
    }//GEN-LAST:event_teraflu_chkboxActionPerformed

    private void aferin_chkboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aferin_chkboxActionPerformed
        // TODO add your handling code here:
         parol_chkbox.setSelected(false);
        teraflu_chkbox.setSelected(false);
        majezik_chkbox.setSelected(false);
        sistenol_chkbox.setSelected(false);
    }//GEN-LAST:event_aferin_chkboxActionPerformed

    private void hst_soyadiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hst_soyadiActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_hst_soyadiActionPerformed

    private void hst_yasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hst_yasActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_hst_yasActionPerformed

    private void siklikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siklikActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_siklikActionPerformed

    private void parol_chkboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parol_chkboxActionPerformed
     aferin_chkbox.setSelected(false);
        teraflu_chkbox.setSelected(false);
        majezik_chkbox.setSelected(false);
        sistenol_chkbox.setSelected(false);
    }//GEN-LAST:event_parol_chkboxActionPerformed

    private void majezik_chkboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_majezik_chkboxActionPerformed
       aferin_chkbox.setSelected(false);
        sistenol_chkbox.setSelected(false);
        parol_chkbox.setSelected(false);
        teraflu_chkbox.setSelected(false);
    }//GEN-LAST:event_majezik_chkboxActionPerformed

    private void sistenol_chkboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sistenol_chkboxActionPerformed
        // TODO add your handling code here:
         aferin_chkbox.setSelected(false);
        teraflu_chkbox.setSelected(false);
        majezik_chkbox.setSelected(false);
        parol_chkbox.setSelected(false);
    }//GEN-LAST:event_sistenol_chkboxActionPerformed

    private void iyi_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iyi_boxActionPerformed
        // TODO add your handling code here:
        kotu_box.setSelected(false);
        
    }//GEN-LAST:event_iyi_boxActionPerformed

    private void kotu_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kotu_boxActionPerformed
        // TODO add your handling code here:
        iyi_box.setSelected(false);
    }//GEN-LAST:event_kotu_boxActionPerformed

    private void gonderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gonderActionPerformed
        // TODO add your handling code here:
         Boolean etki = false;
         if(kotu_box.isSelected()){
             etki = false;
         }      
                  
         
         
         if(etki == true){
             System.out.println("DURUMDA BİR ANORMALLİK YOK GERİ DÖNÜTÜNÜZ İÇİN TEŞEKKÜR EDERİZ");
             System.exit(WIDTH);
         }
         
         
         
         else{
             try {
                 String adi = hst_adi.getText();
                 String soyadi= hst_soyadi.getText();
                 String yas=hst_yas.getText();
                 int yas_y = Integer.parseUnsignedInt(yas);
                 
                 //burası ilac seçimiminin yapılıp kontrol edildiği yerdir. hangi ilac seçildiyse onu ekrana bastırır.
                 String ilac="";
                 int ilac_id=0;
                 if(aferin_chkbox.isSelected()){
                     ilac="AFERİN";
                     ilac_id = 4;
                 }
                 else if(sistenol_chkbox.isSelected()){
                     ilac="SİSTENOL";
                     ilac_id = 5;
                 }
                 
                 else if(parol_chkbox.isSelected()){
                     ilac="PAROL";
                     ilac_id = 1;
                     
                 }
                 else if(teraflu_chkbox.isSelected()){
                     ilac="TERAFLU";
                     ilac_id = 3;
                 }
                 else if(majezik_chkbox.isSelected()){
                     ilac="MAJEZİK";
                     ilac_id = 2;
                     //majezik seçiliyse
                 }
                 else{
                     System.out.println("HATA LÜTFEN BİR İLAC SEÇİNİZ");
                 }
                 
                 System.out.println(ilac);
                 
                 //İlaç kullanım sıklığının tuttulduğu yer
                 String sıklık = siklik.getSelectedItem().toString();
                 int sıklık_y = Integer.parseUnsignedInt(sıklık);
                 System.out.println("sıklık durumu " +sıklık_y);
                 
                 //Hastalık belirtileri ve ayarlamaları
                 
                 int belirti_katssayısı = 0;
                 if(bas_agrisi.isSelected()) {
                     belirti_katssayısı = 3;
                 }
                 else if(mide_bulantisi.isSelected()){
                     belirti_katssayısı = 4;
                     
                 }
                 else if(bas_dönmesi.isSelected()){
                     belirti_katssayısı = 2;
                 }
                 else if(istah_chcboz.isSelected()){
                     belirti_katssayısı = 1;
                 }
                 else if(baygın_chcbx.isSelected()){
                     belirti_katssayısı = 5;
                 }
                 else{
                     System.out.println("BAŞKA BELİRTİLER  GÖTERİYORSANIZ LÜTFEN İLEŞİM HATTIMIZI KULLANINIZ!!)");
                 }
                 
                 
                 
                 // -----------ÇEşitili tanımlamalr ve katsayılar alındı ve işleme sokup puan değeri hesaplanma yeri hemen aşağıdadır. Güncel puan hesabı burda yapılır.
                 
                 //GÜCEL OLAN İLAC PUANINI VERİTABANINDAN ÇEK!!!
                 
                 
                 
                 db_work eski = new db_work();
                 
                 int yeni_puan = eski.eskipuan_Cekme(ilac_id);
                 yeni_puan = belirti_katssayısı*10+yeni_puan + sıklık_y*5;
                 
                                
                 
                 
                 
                 
                 
                 if (yeni_puan < 500){
                     System.out.println(" yeni puan = "+yeni_puan);
                     eski.puan_güncelleme(yeni_puan, ilac_id);
                     
                     JOptionPane.showMessageDialog(rootPane, "İLAC ŞİKAYETLERİ KRİTİK SEVİYEDE DEĞİLDİR ŞİKAYETİNİZ DİKKATE ALINMIŞTIR KULLANMANIZDA BİR SAKINCA YOKTUR !!");
                     System.exit(WIDTH);
                 }
                 else{
                     JOptionPane.showMessageDialog(rootPane, "İLAC ŞİKAYETLERİ KRİTİK SEVİYEYE GELDİ İLACI ÜRETİMDEN KALDIRILACAKTIR !!");
                     
                     System.out.println(yeni_puan);
                     eski.puan_güncelleme(yeni_puan, ilac_id);
                     System.exit(WIDTH);
                 }
                 
                 
                 
                 try {
                     //// --- AŞAĞIDA YENİ GELEN BİLGİLERİN EKLENMESİ İŞLEMİ GERÇEKLEŞİYOR
                     
                     eski.yeni_ekle(adi, soyadi, yas_y);
                 } catch (SQLException ex) {
                     Logger.getLogger(anket_arayüz.class.getName()).log(Level.SEVERE, null, ex);
                 }
                 
                 
                 
                 
                 
                 
                 
             } catch (SQLException ex) {
                 Logger.getLogger(anket_arayüz.class.getName()).log(Level.SEVERE, null, ex);
             }
                       
            
            
         }      
    
    }//GEN-LAST:event_gonderActionPerformed

    private void bas_dönmesiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bas_dönmesiActionPerformed
        // TODO add your handling code here:
        bas_agrisi.setSelected(false);
        istah_chcboz.setSelected(false);
        mide_bulantisi.setSelected(false);
        baygın_chcbx.setSelected(false);
    }//GEN-LAST:event_bas_dönmesiActionPerformed

    private void bas_agrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bas_agrisiActionPerformed
        // TODO add your handling code here:
        bas_dönmesi.setSelected(false);
        istah_chcboz.setSelected(false);
        mide_bulantisi.setSelected(false);
        baygın_chcbx.setSelected(false);
    }//GEN-LAST:event_bas_agrisiActionPerformed

    private void istah_chcbozActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_istah_chcbozActionPerformed
        // TODO add your handling code here:
        bas_agrisi.setSelected(false);
        bas_dönmesi.setSelected(false);
        mide_bulantisi.setSelected(false);
        baygın_chcbx.setSelected(false);
    }//GEN-LAST:event_istah_chcbozActionPerformed

    private void mide_bulantisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mide_bulantisiActionPerformed
        // TODO add your handling code here:
        bas_agrisi.setSelected(false);
        istah_chcboz.setSelected(false);
        bas_dönmesi.setSelected(false);
        baygın_chcbx.setSelected(false);
    }//GEN-LAST:event_mide_bulantisiActionPerformed

    private void baygın_chcbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baygın_chcbxActionPerformed
        // TODO add your handling code here:
        bas_agrisi.setSelected(false);
        istah_chcboz.setSelected(false);
        mide_bulantisi.setSelected(false);
        bas_dönmesi.setSelected(false);
    }//GEN-LAST:event_baygın_chcbxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(anket_arayüz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(anket_arayüz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(anket_arayüz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(anket_arayüz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                  new anket_arayüz().setVisible(true);
                  
           
            }         

            
           
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox aferin_chkbox;
    private javax.swing.JCheckBox bas_agrisi;
    private javax.swing.JCheckBox bas_dönmesi;
    private javax.swing.JCheckBox baygın_chcbx;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton gonder;
    private javax.swing.JTextField hst_adi;
    private javax.swing.JTextField hst_soyadi;
    private javax.swing.JTextField hst_yas;
    private javax.swing.JCheckBox istah_chcboz;
    private javax.swing.JCheckBox iyi_box;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JCheckBox kotu_box;
    private javax.swing.JCheckBox majezik_chkbox;
    private javax.swing.JCheckBox mide_bulantisi;
    private javax.swing.JCheckBox parol_chkbox;
    private javax.swing.JComboBox<String> siklik;
    private javax.swing.JCheckBox sistenol_chkbox;
    private javax.swing.JCheckBox teraflu_chkbox;
    // End of variables declaration//GEN-END:variables
}
